server:
  port: 8088

spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    url: jdbc:h2:./data/test;AUTO_SERVER=TRUE
  h2:
    console:
      path: /h2-console
      enabled: true

#业务配置
biz:
  config: test


